using FlashSeat.Observability;
using FlashSeat.Payment.Application;
using MassTransit;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
namespace FlashSeat.Payment.Infrastructure;
public static class DependencyInjection
{
    public static IServiceCollection AddPaymentInfrastructure(this IServiceCollection services, IConfiguration configuration)
    {
        var connection = configuration.GetConnectionString("PaymentDb") ?? throw new InvalidOperationException("PaymentDb is required.");
        services.Configure<PayOSOptions>(configuration.GetSection(PayOSOptions.SectionName));
        services.AddDbContext<PaymentDbContext>(x => x.UseNpgsql(connection)); services.AddSingleton(TimeProvider.System); services.AddScoped<IPaymentService, PaymentService>(); services.AddHostedService<ExpiredPaymentLinkWorker>();
        services.AddHttpContextAccessor();
        services.AddHttpClient("booking", client => client.BaseAddress = new Uri(configuration["Services:Booking"] ?? "http://booking-api:8080"));
        services.AddHttpClient<IPayOSClient, PayOSClient>(client =>
        {
            client.BaseAddress = new Uri(configuration[$"{PayOSOptions.SectionName}:BaseUrl"] ?? "https://api-merchant.payos.vn");
            client.Timeout = TimeSpan.FromSeconds(15);
        });
        services.AddMassTransit(x =>
        {
            x.AddEntityFrameworkOutbox<PaymentDbContext>(o => { o.UsePostgres(); o.UseBusOutbox(); });
            x.UsingRabbitMq((context, cfg) => cfg.Host(configuration["RabbitMq:Host"] ?? "rabbitmq", "/", h => { h.Username(configuration["RabbitMq:Username"] ?? "flashseat"); h.Password(configuration["RabbitMq:Password"] ?? "flashseat-local"); }));
        });
        services.AddFlashSeatAuthentication(configuration); services.AddHealthChecks().AddNpgSql(connection, tags: ["ready"]); return services;
    }
    public static async Task InitializePaymentDatabaseAsync(this IServiceProvider services, bool useMigrations)
    {
        await using var scope = services.CreateAsyncScope();
        var db = scope.ServiceProvider.GetRequiredService<PaymentDbContext>();
        if (useMigrations) await db.Database.MigrateAsync();
        else await db.Database.EnsureCreatedAsync();
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "OrderCode" bigint NOT NULL DEFAULT 0;
            UPDATE payments SET "OrderCode" = (100000 + floor(random() * 899999))::bigint WHERE "OrderCode" = 0;
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "PaymentLinkId" character varying(100);
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "CheckoutUrl" character varying(2000);
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "QrCode" character varying(2000);
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "PaymentLinkExpiresAt" timestamp with time zone;
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "ProviderReference" character varying(200);
            ALTER TABLE payments ADD COLUMN IF NOT EXISTS "ProviderStatus" character varying(40);
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_payments_OrderCode" ON payments ("OrderCode") WHERE "OrderCode" <> 0;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_payments_PaymentLinkId" ON payments ("PaymentLinkId") WHERE "PaymentLinkId" IS NOT NULL;
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_payments_ProviderReference" ON payments ("ProviderReference") WHERE "ProviderReference" IS NOT NULL;
            CREATE TABLE IF NOT EXISTS payment_webhook_receipts ("Id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, "EventKey" character varying(128) NOT NULL, "PaymentId" uuid NOT NULL, "OrderCode" bigint NOT NULL, "ReceivedAt" timestamp with time zone NOT NULL);
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_payment_webhook_receipts_EventKey" ON payment_webhook_receipts ("EventKey");
        """);
    }
}
