import { useEffect, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import * as signalR from '@microsoft/signalr';
import { api, date, money, saveAuth } from './api';
export function HomePage(){const [search,setSearch]=useState('');const query=useQuery({queryKey:['events',search],queryFn:()=>api.events(search)});return <><section className="hero"><div><p className="eyebrow">LIVE · NHANH · AN TOÀN</p><h1>Chỗ ngồi tuyệt vời.<br/><em>Khoảnh khắc không quên.</em></h1><p>Khám phá sự kiện nổi bật. Giữ ghế tức thời. Không lo trùng vé.</p><form className="search" onSubmit={e=>e.preventDefault()}><label className="sr-only" htmlFor="search">Tìm sự kiện</label><input id="search" placeholder="Tìm nghệ sĩ, địa điểm..." value={search} onChange={e=>setSearch(e.target.value)}/></form></div><div className="orb" aria-hidden="true">FS</div></section><section><div className="section-head"><div><p className="eyebrow">SẮP DIỄN RA</p><h2>Sự kiện nổi bật</h2></div></div>{query.isLoading?<div className="grid"><Skeleton/><Skeleton/><Skeleton/></div>:query.isError?<ErrorState retry={()=>query.refetch()}/>:query.data?.items.length===0?<p className="empty">Không tìm thấy sự kiện phù hợp.</p>:<div className="grid">{query.data?.items.map(event=><article className="card" key={event.id}><img src={event.imageUrl} alt=""/><div className="card-body"><p className="eyebrow">{date(event.startsAt)}</p><h3>{event.name}</h3><p>{event.venueName}</p><div className="card-foot"><strong>Từ {money(event.minPrice)}</strong><Link aria-label={`Xem ${event.name}`} to={`/events/${event.id}`}>Chi tiết →</Link></div></div></article>)}</div>}</section></>}
export function EventDetailPage(){const {id=''}=useParams();const q=useQuery({queryKey:['event',id],queryFn:()=>api.event(id)});if(q.isLoading)return <Skeleton/>;if(!q.data)return <ErrorState retry={()=>q.refetch()}/>;const e=q.data;return <section className="detail"><div className="banner" style={{backgroundImage:`linear-gradient(90deg,rgba(8,11,25,.92),rgba(8,11,25,.15)),url(${e.imageUrl})`}}><div><p className="eyebrow">{date(e.startsAt)}</p><h1>{e.name}</h1><p>{e.venueName} · {e.address}</p><Link className="button" to={`/events/${e.id}/seats`}>Chọn ghế</Link></div></div><div className="prose"><h2>Về sự kiện</h2><p>{e.description}</p><h2>Thông tin</h2><p>Mở bán đến {date(e.salesEndAt)} · Giá từ {money(Math.min(...e.seats.map(s=>s.price)))}</p></div></section>}
const authSchema=z.object({fullName:z.string().min(2).optional(),email:z.string().email('Email không hợp lệ'),password:z.string().min(10,'Mật khẩu tối thiểu 10 ký tự')});type AuthForm=z.infer<typeof authSchema>;
export function AuthPage(){const [register,setRegister]=useState(false);const nav=useNavigate();const form=useForm<AuthForm>({resolver:zodResolver(authSchema)});const mutation=useMutation({mutationFn:(v:AuthForm)=>register?api.register(v.email,v.password,v.fullName!):api.login(v.email,v.password),onSuccess:r=>{saveAuth(r);nav('/')}});return <section className="auth"><div><p className="eyebrow">CHÀO MỪNG</p><h1>{register?'Tạo tài khoản':'Trở lại FlashSeat'}</h1><form onSubmit={form.handleSubmit(v=>mutation.mutate(v))}>{register&&<label>Họ tên<input {...form.register('fullName')}/><small>{form.formState.errors.fullName?.message}</small></label>}<label>Email<input type="email" {...form.register('email')}/><small>{form.formState.errors.email?.message}</small></label><label>Mật khẩu<input type="password" {...form.register('password')}/><small>{form.formState.errors.password?.message}</small></label>{mutation.isError&&<p className="error">Đăng nhập không thành công.</p>}<button className="button" disabled={mutation.isPending}>{mutation.isPending?'Đang xử lý...':register?'Đăng ký':'Đăng nhập'}</button></form><button className="text-button" onClick={()=>setRegister(!register)}>{register?'Đã có tài khoản? Đăng nhập':'Chưa có tài khoản? Đăng ký'}</button></div></section>}
export function SeatPage(){const {id=''}=useParams();const nav=useNavigate();const qc=useQueryClient();const [selected,setSelected]=useState<string[]>([]);const event=useQuery({queryKey:['event',id],queryFn:()=>api.event(id)});const availability=useQuery({queryKey:['availability',id],queryFn:()=>api.availability(id),refetchInterval:15000});useEffect(()=>{const token=localStorage.getItem('accessToken');const connection=new signalR.HubConnectionBuilder().withUrl('/hubs/seat-availability',{accessTokenFactory:()=>token??''}).withAutomaticReconnect().build();connection.on('SeatsHeld',()=>qc.invalidateQueries({queryKey:['availability',id]}));connection.on('SeatsReleased',()=>qc.invalidateQueries({queryKey:['availability',id]}));connection.on('SeatsBooked',()=>qc.invalidateQueries({queryKey:['availability',id]}));connection.onreconnected(()=>{connection.invoke('JoinEvent',id);qc.invalidateQueries({queryKey:['availability',id]})});connection.start().then(()=>connection.invoke('JoinEvent',id)).catch(()=>undefined);return()=>{connection.invoke('LeaveEvent',id).catch(()=>undefined).finally(()=>connection.stop())}},[id,qc]);const hold=useMutation({mutationFn:()=>api.hold(id,selected),onSuccess:async h=>{const b=await api.booking(h.id);const p=await api.pay(b.id,'Success');qc.invalidateQueries({queryKey:['availability',id]});alert(`Thanh toán ${p.status}. Mã vé ${b.bookingNumber}`);nav('/bookings')},onError:()=>{setSelected([]);availability.refetch()}});if(!event.data)return <Skeleton/>;const states=new Map(availability.data?.map(x=>[x.seatId,x.status]));const total=event.data.seats.filter(s=>selected.includes(s.id)).reduce((a,s)=>a+s.price,0);return <section><p className="eyebrow">CHỌN GHẾ</p><h1>{event.data.name}</h1><div className="seat-layout"><div><div className="stage">SÂN KHẤU</div><div className="seat-grid">{event.data.seats.map(s=>{const state=states.get(s.id)??'Available';const chosen=selected.includes(s.id);return <button key={s.id} className={`seat ${state.toLowerCase()} ${chosen?'selected':''}`} disabled={state!=='Available'} aria-label={`Ghế ${s.row}${s.number}, ${s.section}, ${money(s.price)}, ${state==='Available'?'còn trống':state}`} onClick={()=>setSelected(x=>chosen?x.filter(v=>v!==s.id):x.length<6?[...x,s.id]:x)}>{s.row}{s.number}</button>})}</div></div><aside className="summary"><h2>Đơn của bạn</h2><p>{selected.length} ghế đã chọn</p><strong>{money(total)}</strong><button className="button" disabled={!selected.length||hold.isPending} onClick={()=>hold.mutate()}>{hold.isPending?'Đang giữ ghế...':'Giữ ghế & thanh toán'}</button>{hold.isError&&<p className="error">Ghế vừa được người khác giữ. Vui lòng chọn lại.</p>}</aside></div></section>}
export function MyBookingsPage(){const q=useQuery({queryKey:['bookings'],queryFn:api.bookings});return <section><p className="eyebrow">TÀI KHOẢN</p><h1>Vé của tôi</h1>{q.isLoading?<Skeleton/>:q.data?.length===0?<p className="empty">Bạn chưa có vé.</p>:<div className="tickets">{q.data?.map(b=><article className="ticket" key={b.id}><div><p className="eyebrow">{b.status}</p><h2>{b.bookingNumber}</h2><p>{date(b.createdAt)} · {b.items.length} ghế</p></div><strong>{money(b.totalAmount)}</strong></article>)}</div>}</section>}
function Skeleton(){return <div className="skeleton" aria-label="Đang tải"/>}function ErrorState({retry}:{retry:()=>unknown}){return <div className="empty"><p>Không thể tải dữ liệu.</p><button className="ghost" onClick={retry}>Thử lại</button></div>}
